pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk   'JDK'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/masiurraheman91/Selenium-java'
            }
        }

        stage('Build') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
    }
}
