pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'jdk21'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/masiurraheman91/Selenium-java'
            }
        }

        stage('Build') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('cucumber_bdd') {
                    bat 'mvn package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('cucumber_bdd') {
                    bat 'docker build -t cucumber-framework .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                bat 'docker run --rm cucumber-framework'
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
    }
}